; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wemos_d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_port = COM14
upload_speed = 921600
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m3m.ld
board_build.flash_mode = qio
board_build.cpu_frequency = 160
lib_deps =
  Arduino
  littlefs
 	https://github.com/Bodmer/TFT_eSPI/archive/refs/heads/master.zip

build_flags =
	-D SUPPORT_TRANSACTIONS
  -D USER_SETUP_LOADED=1
	-D ST7735_DRIVER
	-D TFT_CS=16
	-D TFT_DC=0
	-D TFT_RST=-1
	-D TFT_MOSI=13
	-D TFT_MISO=-1
	-D TFT_SCLK=14
  -D TFT_BL=-1
  -D TOUCH_CS=-1
  -D TFT_WIDTH=160
  -D TFT_HEIGHT=160
  -D LOAD_FF
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
  -D LOAD_FONT7
	-D LOAD_GFXFF
	-D SPI_FREQUENCY=10000000
	-D SPI_READ_FREQUENCY=10000000
